[book]
title = "Kokage"
description = "A user tutorial for the Kokage crates"
authors = ["Alex Stokes"]
language = "en"
src = "src"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/ralexstokes/kokage"
additional-css = ["api-link.css"]
additional-js = ["api-link.js"]
